In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/car_price_performance.csv')

In [4]:
 df.head()

     Brand  Price  Horsepower  Fuel Efficiency
0  Brand C  91942         382             15.3
1  Brand A  70075         197             32.6
2  Brand C  84524         188             34.9
3  Brand E  68939         258             15.1
4  Brand X  66505         277             13.0

In [10]:
brand_avg_price = df.groupby('Brand')['Price'].mean().sort_values()
brand_avg_price

Brand
Brand W    63034.557018
Brand E    63712.542601
Brand Y    63880.171569
Brand A    64224.495370
Brand B    64686.641350
Brand C    64707.967890
Brand Z    65244.331818
Brand X    65405.884259
Brand D    65498.701681
Name: Price, dtype: float64

In [11]:
brand_mapping = {brand: i for i, brand in enumerate(brand_avg_price.index, start=1)}
brand_mapping

{'Brand W': 1,
 'Brand E': 2,
 'Brand Y': 3,
 'Brand A': 4,
 'Brand B': 5,
 'Brand C': 6,
 'Brand Z': 7,
 'Brand X': 8,
 'Brand D': 9}

In [13]:
encoded_brands = []
for b in df['Brand']:
    encoded_value = brand_mapping[b]
    encoded_brands.append(encoded_value)

In [14]:
df['Encoded_Brand'] = encoded_brands
df[['Brand', 'Encoded_Brand']].drop_duplicates()
df

        Brand  Price  Horsepower  Fuel Efficiency  Encoded_Brand
0     Brand C  91942         382             15.3              6
1     Brand A  70075         197             32.6              4
2     Brand C  84524         188             34.9              6
3     Brand E  68939         258             15.1              2
4     Brand X  66505         277             13.0              8
...       ...    ...         ...              ...            ...
1995  Brand Z  34535         196             15.2              7
1996  Brand C  35215         377             25.3              6
1997  Brand E  72980         294             21.8              2
1998  Brand Z  55921         443             11.0              7
1999  Brand B  95051         225             12.4              5

[2000 rows x 5 columns]

In [15]:
min_brand = df['Encoded_Brand'].min()
max_brand = df['Encoded_Brand'].max()
df['Scaled_Brand'] = (df['Encoded_Brand'] - min_brand) / (max_brand - min_brand)
df

        Brand  Price  Horsepower  Fuel Efficiency  Encoded_Brand  Scaled_Brand
0     Brand C  91942         382             15.3              6         0.625
1     Brand A  70075         197             32.6              4         0.375
2     Brand C  84524         188             34.9              6         0.625
3     Brand E  68939         258             15.1              2         0.125
4     Brand X  66505         277             13.0              8         0.875
...       ...    ...         ...              ...            ...           ...
1995  Brand Z  34535         196             15.2              7         0.750
1996  Brand C  35215         377             25.3              6         0.625
1997  Brand E  72980         294             21.8              2         0.125
1998  Brand Z  55921         443             11.0              7         0.750
1999  Brand B  95051         225             12.4              5         0.500

[2000 rows x 6 columns]

In [16]:
min_hp = df['Horsepower'].min()
max_hp = df['Horsepower'].max()
df['Scaled_Horsepower'] = (df['Horsepower'] - min_hp) / (max_hp - min_hp)
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded_Brand,Scaled_Brand,Scaled_Horsepower
0,Brand C,91942,382,15.3,6,0.625,0.7050
1,Brand A,70075,197,32.6,4,0.375,0.2425
2,Brand C,84524,188,34.9,6,0.625,0.2200
3,Brand E,68939,258,15.1,2,0.125,0.3950
4,Brand X,66505,277,13.0,8,0.875,0.4425
...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.750,0.2400
1996,Brand C,35215,377,25.3,6,0.625,0.6925
1997,Brand E,72980,294,21.8,2,0.125,0.4850
1998,Brand Z,55921,443,11.0,7,0.750,0.8575
1999,Brand B,95051,225,12.4,5,0.500,0.3125

In [17]:
min = df['Fuel Efficiency'].min()
max = df['Fuel Efficiency'].max()
df['Scaled_Fuel_Efficiency'] = (df['Fuel Efficiency'] - min) / (max - min)
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded_Brand,Scaled_Brand,Scaled_Horsepower,Scaled_Fuel_Efficiency
0,Brand C,91942,382,15.3,6,0.625,0.7050,0.212
1,Brand A,70075,197,32.6,4,0.375,0.2425,0.904
2,Brand C,84524,188,34.9,6,0.625,0.2200,0.996
3,Brand E,68939,258,15.1,2,0.125,0.3950,0.204
4,Brand X,66505,277,13.0,8,0.875,0.4425,0.120
...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.750,0.2400,0.208
1996,Brand C,35215,377,25.3,6,0.625,0.6925,0.612
1997,Brand E,72980,294,21.8,2,0.125,0.4850,0.472
1998,Brand Z,55921,443,11.0,7,0.750,0.8575,0.040
1999,Brand B,95051,225,12.4,5,0.500,0.3125,0.096

In [18]:
df['Performance_Index'] = df['Horsepower'] * df['Fuel Efficiency']
df

,Brand,Price,Horsepower,Fuel Efficiency,Encoded_Brand,Scaled_Brand,Scaled_Horsepower,Scaled_Fuel_Efficiency,Performance_Index
0,Brand C,91942,382,15.3,6,0.625,0.7050,0.212,5844.6
1,Brand A,70075,197,32.6,4,0.375,0.2425,0.904,6422.2
2,Brand C,84524,188,34.9,6,0.625,0.2200,0.996,6561.2
3,Brand E,68939,258,15.1,2,0.125,0.3950,0.204,3895.8
4,Brand X,66505,277,13.0,8,0.875,0.4425,0.120,3601.0
...,...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.750,0.2400,0.208,2979.2
1996,Brand C,35215,377,25.3,6,0.625,0.6925,0.612,9538.1
1997,Brand E,72980,294,21.8,2,0.125,0.4850,0.472,6409.2
1998,Brand Z,55921,443,11.0,7,0.750,0.8575,0.040,4873.0
1999,Brand B,95051,225,12.4,5,0.500,0.3125,0.096,2790.0

In [19]:
print("final_Table")
df

final_Table

,Brand,Price,Horsepower,Fuel Efficiency,Encoded_Brand,Scaled_Brand,Scaled_Horsepower,Scaled_Fuel_Efficiency,Performance_Index
0,Brand C,91942,382,15.3,6,0.625,0.7050,0.212,5844.6
1,Brand A,70075,197,32.6,4,0.375,0.2425,0.904,6422.2
2,Brand C,84524,188,34.9,6,0.625,0.2200,0.996,6561.2
3,Brand E,68939,258,15.1,2,0.125,0.3950,0.204,3895.8
4,Brand X,66505,277,13.0,8,0.875,0.4425,0.120,3601.0
...,...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.750,0.2400,0.208,2979.2
1996,Brand C,35215,377,25.3,6,0.625,0.6925,0.612,9538.1
1997,Brand E,72980,294,21.8,2,0.125,0.4850,0.472,6409.2
1998,Brand Z,55921,443,11.0,7,0.750,0.8575,0.040,4873.0
1999,Brand B,95051,225,12.4,5,0.500,0.3125,0.096,2790.0

In [22]:
print("final_Table")
final_Table = df # Assign the dataframe 'df' to the variable 'final_Table'
final_Table.to_csv('final_car_table.csv', index=False)
from google.colab import files
files.download('final_car_table.csv')

final_Table